language: go

os:
- linux
- osx

go:
- "1.9.x"
install: make install
script: make build version="${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}" && make test
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then mv bin/aws-profile-utils bin/aws-profile-utils-${TRAVIS_OS_NAME}-${TRAVIS_BUILD_NUMBER} ; fi
- if [[ "$TRAVIS_BRANCH" != "master" ]]; then mv bin/aws-profile-utils bin/aws-profile-utils-${TRAVIS_OS_NAME} ; fi
deploy:
  - provider: gcs
    access_key_id: "GOOGXSXJIII432RYYGT7DNP5"
    secret_access_key:
      secure: "IqPBYctNlPMAKAn8VjLaq/HzZRNVP8kQ/6+6trvsqA1nO3B525QcKK+1efHOGIKt5K9u9wrvwAM2AC4wto438RoyeWiZxKlZtzHGJRKuxjdN/Q072kU1ndsdOhflLZQuWk5uVWk6EIJnh8vlMqe7e2asK7HEuyY6TC+rbfPjVFix7iKFY9yFD7aOORrG1HpyFHFIXf4mUWudfHqCq4RDrIFRQJd9MeLiVA6GUE0eC0m941lnHdSmQbcda5KYU7lHJta1op/CnRVhswb57ESs0KLVtS+uII3wp/TwYafw1ZGwzb4ekrX+p/glcGdFLXkyXXg8hKkOe2IM3zDWvrEhL10m3VILmLKUd8Wv4JdzWXb1Tgm+yNkhFkqtq+vTRWKP1pXaXW8cZYOpbzJjzsRnnfVeeSlpSzgmAtlSZI7qqcqMV/4BQN62ZEGldHFKZS3Yhcjd+am1CymlKEbvXq07yqOlzP5RC+B3lPCWgJPfKG4Rf3DvrpK4yc1qjCA0Uv24kZDSiLTE84hsNkLfjimOqyZR+6kBtXrXIhBeMWjdTKfVQ8iq12HhA9vORkYsN4XXqQ3y7SHQpP60tcaxAGFQgnFuUiZISRezr8oma7DReN2gNAE6WmuEgTHr7NpKmPd90Fp61Wkw+UKSHE62hTfngRnKICvdcm3sYwP09mjxE/E="
    bucket: "aws-profile-utils-master"
    skip_cleanup: true
    acl: public-read
    local-dir: bin
    on:
      branch: master
  - provider: releases
    api_key:
      secure: "rjIAHf2KXJkAGJhTTibjWHwJ8TQn7K+jYjMe6rMzPNvZ+nk7SDuso1r1ohRtNBHMaQfxESUZrPn7+H4/wBnJsgqnpTgF4xbRYftki7BcJUxD8etUr0iPMpraDpkwn4PmX5MO36VRtAgR51vQYl8eaNdsdE32xO3HTutVj/b51bjZrs/mx04t/rcG4Sv2Ce3P83B8W5H0uK3wCyVO7UbYEh3DQU3U90dyBeXV81CnzzUOL7JHn7t0PQ4WPbJfhR7RpJ1nJ66gL2W74DHemYKpn4mcnWd5N+q6o4Fn7l7O3ci6tgo1MzaAdoqaVCOJnaoC/AxUblZ1KxI0v1Ouv2uNqCzBCCPOcRSyvlhDnEjmqjDBGg9KowAH7TLBn+W0ZwN/2FfnsxLHMkLnk/amG9gAwqum28ryXcGPnYi5TAVV9HM3ZcHYIvNXfZmbCO61V3E8SKViXHaeJj9DvCt5WQqp2jI/nRyQ1+hL8mw+sLnxoFO61Wl9e9hkpe34nkxtyFy5IQdur4g9m1Se8YJySf+4iDQosQU1wr0okS5KNScNQYF3UX9qGmh6RNOR7melPxlAEBRPm7cJZInj4hInA1BHUNh170Cb092zgmvoaqPva/axCgkH0wZifirD+Fboe6Uk8S9PqyIVboMTW3KaE5YHdibTD2uX2S9kz69VnalmGPI="
    file: "bin/aws-profile-utils-${TRAVIS_OS_NAME}"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9\.]+$
