language: go

os:
- linux
- osx

go:
- "1.9.x"
install: make install
script: make build version="${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}" && make test
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then mv bin/aws-profile-utils bin/aws-profile-utils-${TRAVIS_OS_NAME}-${TRAVIS_BUILD_NUMBER} ; fi
- if [[ "$TRAVIS_BRANCH" != "master" ]]; then mv bin/aws-profile-utils bin/aws-profile-utils-${TRAVIS_OS_NAME} ; fi
deploy:
  - provider: bintray
    file: bintray-descriptor.json
    user: hpcsc
    key:
      secure: eRZjMIrHJnvcUj+ldh8WHN3WVElVah4FJIsUlYouQR+fT1t0SXJpOUOml9UdR9gSe4alD7GIrMpkMrF3s9mI7o5/jGTYeuY2vB6n2mqWtJZEBcWy+mFWzH1wMbsqTsLVx5CHWVymXGYDyTjqZsqVsPLK8ZR3y9NKDp3YnPZtb8u/bAdCh4KphBMqVH23uAn/dGAUq4I9b6F16nMGQzAcPM+oH90xn2ek9wPQTCsqbe1jzlFmUjZqYypAjZ6MPaVaWpFAWXzo0syYxrLG8sRTIN3rinAlgF4g+XMXJgb1B2L/Qw+FmK+kCRS5Fjg1Jgb9HyBiK+54bS/rP6VQf4n6BhmW+2II68Swokdd+QKsautWO3umh9Ho1v8n21nkyCukLY4TH428246KrQu+hPemZ5zswXRC0hyvEeUUcg/yewYBGS7Ty+nKXADk7oKvGXBo87kbUTICUGxQ/AbhSkyf0qT0U2WxGxCLQNH52BMlM624bIw6EW35E+LWDGA5KwHCZay/QZThcikK1KM0jrGPZ8RYDRw4zOT2ygMjTsmzWX3NSFa2F1bPOzUqM83vLacadXgjqvJoGzhHLeSYf5D8Muy7gMERiIzyWOKVqtDp4GD59Cz2vWCkEB0/ACHYF5PEc3TY45kJ2plQD0H2obOAfctJCMwWvp8u25F5991i3KQ=
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key:
      secure: "rjIAHf2KXJkAGJhTTibjWHwJ8TQn7K+jYjMe6rMzPNvZ+nk7SDuso1r1ohRtNBHMaQfxESUZrPn7+H4/wBnJsgqnpTgF4xbRYftki7BcJUxD8etUr0iPMpraDpkwn4PmX5MO36VRtAgR51vQYl8eaNdsdE32xO3HTutVj/b51bjZrs/mx04t/rcG4Sv2Ce3P83B8W5H0uK3wCyVO7UbYEh3DQU3U90dyBeXV81CnzzUOL7JHn7t0PQ4WPbJfhR7RpJ1nJ66gL2W74DHemYKpn4mcnWd5N+q6o4Fn7l7O3ci6tgo1MzaAdoqaVCOJnaoC/AxUblZ1KxI0v1Ouv2uNqCzBCCPOcRSyvlhDnEjmqjDBGg9KowAH7TLBn+W0ZwN/2FfnsxLHMkLnk/amG9gAwqum28ryXcGPnYi5TAVV9HM3ZcHYIvNXfZmbCO61V3E8SKViXHaeJj9DvCt5WQqp2jI/nRyQ1+hL8mw+sLnxoFO61Wl9e9hkpe34nkxtyFy5IQdur4g9m1Se8YJySf+4iDQosQU1wr0okS5KNScNQYF3UX9qGmh6RNOR7melPxlAEBRPm7cJZInj4hInA1BHUNh170Cb092zgmvoaqPva/axCgkH0wZifirD+Fboe6Uk8S9PqyIVboMTW3KaE5YHdibTD2uX2S9kz69VnalmGPI="
    file: "bin/aws-profile-utils-${TRAVIS_OS_NAME}"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9\.]+$
